### ISSUE TITLE
setup_githooks.sh fails if run again

### ISSUE THREAD

**Issue by brookskindle** [brookskindle/cathub#3]
setup_githooks.sh doesn't force replace the symlink, which means that anybody running the old version of setup_githooks.sh cannot update to the new version without having to manually remove the hooks copied to .git/hooks.

**This affects the master version of code.**

I ran a git blame and @lancekindle popped up. Can he shed some light on this issue?
4b27f974

**Comment by lancekindle** [comment]
Sure thing. As you've said, my script symbolically links without overwriting the file. I'll see if I can fix that (I'll create a branch fix-symbolic-link)
